//
//  LocationModalityModelTests.swift
//  SensorKit
//
//  Created by Joseph Blau on 1/15/17.
//  Copyright © 2017 Joe Blau. All rights reserved.
//

import XCTest

@testable import SensorKit

// swiftlint:disable type_body_length
class LocationModalityModelTests: XCTestCase {
    let mockLocationModlaityModel = LocationModalityModel(locationCoordinateLatitude: nil,
                                                          locationCoordinateLongitude: nil,
                                                          locationAltitude: nil,
                                                          locationHorizontalAccuracy: nil,
                                                          locationVerticalAccuracy: nil,
                                                          locationCourse: nil,
                                                          locationSpeed: nil,
                                                          locationTimestamp: nil,
                                                          locationFloorLevel: nil,
                                                          beaconProximityUUID: nil,
                                                          beaconMajor: nil,
                                                          beaconMinor: nil,
                                                          beaconProximity: .unknown,
                                                          beaconAccuracy: nil,
                                                          beaconRssi: nil,
                                                          headingMagneticHeading: nil,
                                                          headingTrueHeading: nil,
                                                          headingHeadingAccuracy: nil,
                                                          headingX: nil,
                                                          headingY: nil,
                                                          headingZ: nil,
                                                          headingTimestamp: nil,
                                                          visitArrivalDate: nil,
                                                          visitDepartureDate: nil,
                                                          visitCoordinateLatitude: nil,
                                                          visitCoordinateLongitude: nil,
                                                          visitHorizontalAccuracy: nil,
                                                          placemarkLocationCoordinateLatitude: nil,
                                                          placemarkLocationCoordinateLongitude: nil,
                                                          placemarkLocationAltitude: nil,
                                                          placemarkLocationHorizontalAccuracy: nil,
                                                          placemarkLocationVerticalAccuracy: nil,
                                                          placemarkLocationCourse: nil,
                                                          placemarkLocationSpeed: nil,
                                                          placemarkLocationTimestamp: nil,
                                                          placemarkLocationFloorLevel: nil,
                                                          placemarkRegionIdentifier: nil,
                                                          placemarkTimeZone: nil,
                                                          placemarkAddressDictionary: nil,
                                                          placemarkName: nil,
                                                          placemarkThoroughfare: nil,
                                                          placemarkSubThoroughfare: nil,
                                                          placemarkLocality: nil,
                                                          placemarkSubLocality: nil,
                                                          placemarkAdministrativeArea: nil,
                                                          placemarkSubAdministrativeArea: nil,
                                                          placemarkPostalCode: nil,
                                                          placemarkIsoCountryCode: nil,
                                                          placemarkCountry: nil,
                                                          placemarkInlandWater: nil,
                                                          placemarkOcean: nil,
                                                          placemarkAreasOfInterest: nil)

    func testSensorDescription() {
        XCTAssertEqual(mockLocationModlaityModel.count, mockLocationModlaityModel.descriptionLineCount)
    }

    func testSensorPropertyCount() {
        XCTAssertEqual(mockLocationModlaityModel.count, 52)
    }

    // swiftlint:disable:next function_body_length
    func testCLProximityStringUnknown() {
        let unknownProximity = LocationModalityModel(locationCoordinateLatitude: nil,
                                                     locationCoordinateLongitude: nil,
                                                     locationAltitude: nil,
                                                     locationHorizontalAccuracy: nil,
                                                     locationVerticalAccuracy: nil,
                                                     locationCourse: nil,
                                                     locationSpeed: nil,
                                                     locationTimestamp: nil,
                                                     locationFloorLevel: nil,
                                                     beaconProximityUUID: nil,
                                                     beaconMajor: nil,
                                                     beaconMinor: nil,
                                                     beaconProximity: .unknown,
                                                     beaconAccuracy: nil,
                                                     beaconRssi: nil,
                                                     headingMagneticHeading: nil,
                                                     headingTrueHeading: nil,
                                                     headingHeadingAccuracy: nil,
                                                     headingX: nil,
                                                     headingY: nil,
                                                     headingZ: nil,
                                                     headingTimestamp: nil,
                                                     visitArrivalDate: nil,
                                                     visitDepartureDate: nil,
                                                     visitCoordinateLatitude: nil,
                                                     visitCoordinateLongitude: nil,
                                                     visitHorizontalAccuracy: nil,
                                                     placemarkLocationCoordinateLatitude: nil,
                                                     placemarkLocationCoordinateLongitude: nil,
                                                     placemarkLocationAltitude: nil,
                                                     placemarkLocationHorizontalAccuracy: nil,
                                                     placemarkLocationVerticalAccuracy: nil,
                                                     placemarkLocationCourse: nil,
                                                     placemarkLocationSpeed: nil,
                                                     placemarkLocationTimestamp: nil,
                                                     placemarkLocationFloorLevel: nil,
                                                     placemarkRegionIdentifier: nil,
                                                     placemarkTimeZone: nil,
                                                     placemarkAddressDictionary: nil,
                                                     placemarkName: nil,
                                                     placemarkThoroughfare: nil,
                                                     placemarkSubThoroughfare: nil,
                                                     placemarkLocality: nil,
                                                     placemarkSubLocality: nil,
                                                     placemarkAdministrativeArea: nil,
                                                     placemarkSubAdministrativeArea: nil,
                                                     placemarkPostalCode: nil,
                                                     placemarkIsoCountryCode: nil,
                                                     placemarkCountry: nil,
                                                     placemarkInlandWater: nil,
                                                     placemarkOcean: nil,
                                                     placemarkAreasOfInterest: nil)
        XCTAssertEqual(unknownProximity.beaconProximity.description, "Unknown")
    }

    // swiftlint:disable:next function_body_length
    func testCLProximityStringNear() {
        let nearProximity = LocationModalityModel(locationCoordinateLatitude: nil,
                                                  locationCoordinateLongitude: nil,
                                                  locationAltitude: nil,
                                                  locationHorizontalAccuracy: nil,
                                                  locationVerticalAccuracy: nil,
                                                  locationCourse: nil,
                                                  locationSpeed: nil,
                                                  locationTimestamp: nil,
                                                  locationFloorLevel: nil,
                                                  beaconProximityUUID: nil,
                                                  beaconMajor: nil,
                                                  beaconMinor: nil,
                                                  beaconProximity: .near,
                                                  beaconAccuracy: nil,
                                                  beaconRssi: nil,
                                                  headingMagneticHeading: nil,
                                                  headingTrueHeading: nil,
                                                  headingHeadingAccuracy: nil,
                                                  headingX: nil,
                                                  headingY: nil,
                                                  headingZ: nil,
                                                  headingTimestamp: nil,
                                                  visitArrivalDate: nil,
                                                  visitDepartureDate: nil,
                                                  visitCoordinateLatitude: nil,
                                                  visitCoordinateLongitude: nil,
                                                  visitHorizontalAccuracy: nil,
                                                  placemarkLocationCoordinateLatitude: nil,
                                                  placemarkLocationCoordinateLongitude: nil,
                                                  placemarkLocationAltitude: nil,
                                                  placemarkLocationHorizontalAccuracy: nil,
                                                  placemarkLocationVerticalAccuracy: nil,
                                                  placemarkLocationCourse: nil,
                                                  placemarkLocationSpeed: nil,
                                                  placemarkLocationTimestamp: nil,
                                                  placemarkLocationFloorLevel: nil,
                                                  placemarkRegionIdentifier: nil,
                                                  placemarkTimeZone: nil,
                                                  placemarkAddressDictionary: nil,
                                                  placemarkName: nil,
                                                  placemarkThoroughfare: nil,
                                                  placemarkSubThoroughfare: nil,
                                                  placemarkLocality: nil,
                                                  placemarkSubLocality: nil,
                                                  placemarkAdministrativeArea: nil,
                                                  placemarkSubAdministrativeArea: nil,
                                                  placemarkPostalCode: nil,
                                                  placemarkIsoCountryCode: nil,
                                                  placemarkCountry: nil,
                                                  placemarkInlandWater: nil,
                                                  placemarkOcean: nil,
                                                  placemarkAreasOfInterest: nil)
        XCTAssertEqual(nearProximity.beaconProximity.description, "Near")
    }

    // swiftlint:disable:next function_body_length
    func testCLProximityStringImmediate() {
        let immediateProximity = LocationModalityModel(locationCoordinateLatitude: nil,
                                                       locationCoordinateLongitude: nil,
                                                       locationAltitude: nil,
                                                       locationHorizontalAccuracy: nil,
                                                       locationVerticalAccuracy: nil,
                                                       locationCourse: nil,
                                                       locationSpeed: nil,
                                                       locationTimestamp: nil,
                                                       locationFloorLevel: nil,
                                                       beaconProximityUUID: nil,
                                                       beaconMajor: nil,
                                                       beaconMinor: nil,
                                                       beaconProximity: .immediate,
                                                       beaconAccuracy: nil,
                                                       beaconRssi: nil,
                                                       headingMagneticHeading: nil,
                                                       headingTrueHeading: nil,
                                                       headingHeadingAccuracy: nil,
                                                       headingX: nil,
                                                       headingY: nil,
                                                       headingZ: nil,
                                                       headingTimestamp: nil,
                                                       visitArrivalDate: nil,
                                                       visitDepartureDate: nil,
                                                       visitCoordinateLatitude: nil,
                                                       visitCoordinateLongitude: nil,
                                                       visitHorizontalAccuracy: nil,
                                                       placemarkLocationCoordinateLatitude: nil,
                                                       placemarkLocationCoordinateLongitude: nil,
                                                       placemarkLocationAltitude: nil,
                                                       placemarkLocationHorizontalAccuracy: nil,
                                                       placemarkLocationVerticalAccuracy: nil,
                                                       placemarkLocationCourse: nil,
                                                       placemarkLocationSpeed: nil,
                                                       placemarkLocationTimestamp: nil,
                                                       placemarkLocationFloorLevel: nil,
                                                       placemarkRegionIdentifier: nil,
                                                       placemarkTimeZone: nil,
                                                       placemarkAddressDictionary: nil,
                                                       placemarkName: nil,
                                                       placemarkThoroughfare: nil,
                                                       placemarkSubThoroughfare: nil,
                                                       placemarkLocality: nil,
                                                       placemarkSubLocality: nil,
                                                       placemarkAdministrativeArea: nil,
                                                       placemarkSubAdministrativeArea: nil,
                                                       placemarkPostalCode: nil,
                                                       placemarkIsoCountryCode: nil,
                                                       placemarkCountry: nil,
                                                       placemarkInlandWater: nil,
                                                       placemarkOcean: nil,
                                                       placemarkAreasOfInterest: nil)
        XCTAssertEqual(immediateProximity.beaconProximity.description, "Immediate")
    }

    // swiftlint:disable:next function_body_length
    func testCLProximityStringFar() {
        let farProximity = LocationModalityModel(locationCoordinateLatitude: nil,
                                                 locationCoordinateLongitude: nil,
                                                 locationAltitude: nil,
                                                 locationHorizontalAccuracy: nil,
                                                 locationVerticalAccuracy: nil,
                                                 locationCourse: nil,
                                                 locationSpeed: nil,
                                                 locationTimestamp: nil,
                                                 locationFloorLevel: nil,
                                                 beaconProximityUUID: nil,
                                                 beaconMajor: nil,
                                                 beaconMinor: nil,
                                                 beaconProximity: .far,
                                                 beaconAccuracy: nil,
                                                 beaconRssi: nil,
                                                 headingMagneticHeading: nil,
                                                 headingTrueHeading: nil,
                                                 headingHeadingAccuracy: nil,
                                                 headingX: nil,
                                                 headingY: nil,
                                                 headingZ: nil,
                                                 headingTimestamp: nil,
                                                 visitArrivalDate: nil,
                                                 visitDepartureDate: nil,
                                                 visitCoordinateLatitude: nil,
                                                 visitCoordinateLongitude: nil,
                                                 visitHorizontalAccuracy: nil,
                                                 placemarkLocationCoordinateLatitude: nil,
                                                 placemarkLocationCoordinateLongitude: nil,
                                                 placemarkLocationAltitude: nil,
                                                 placemarkLocationHorizontalAccuracy: nil,
                                                 placemarkLocationVerticalAccuracy: nil,
                                                 placemarkLocationCourse: nil,
                                                 placemarkLocationSpeed: nil,
                                                 placemarkLocationTimestamp: nil,
                                                 placemarkLocationFloorLevel: nil,
                                                 placemarkRegionIdentifier: nil,
                                                 placemarkTimeZone: nil,
                                                 placemarkAddressDictionary: nil,
                                                 placemarkName: nil,
                                                 placemarkThoroughfare: nil,
                                                 placemarkSubThoroughfare: nil,
                                                 placemarkLocality: nil,
                                                 placemarkSubLocality: nil,
                                                 placemarkAdministrativeArea: nil,
                                                 placemarkSubAdministrativeArea: nil,
                                                 placemarkPostalCode: nil,
                                                 placemarkIsoCountryCode: nil,
                                                 placemarkCountry: nil,
                                                 placemarkInlandWater: nil,
                                                 placemarkOcean: nil,
                                                 placemarkAreasOfInterest: nil)
        XCTAssertEqual(farProximity.beaconProximity.description, "Far")
    }
}
// swiftlint:enable type_body_length
